export class ProdutosServices {
    constructor(client) {
        this.client = client;
    }

    async updateProdutoAvulso({
        IDPRODUTO, DSNOME, IDGRUPOEMPRESARIAL, NUNCM, IDUND, UND,
        PRECOCUSTO, PRECOVENDA, IDSUBGRUPO, IDFABRICANTE, IDFORNECEDOR,
        NUREFERENCIA, IDCOR, IDTAMANHO, IDCATEGORIAPEDIDO, IDTIPOTECIDO,
        IDESTILO, IDLOCALEXPOSICAO, IDCATEGORIAS, IDTIPOPRODUTOFISCAL,
        IDFONTEPRODUTOFISCAL, STECOMMERCE, STREDESOCIAL
    }) {
        if (!IDPRODUTO) {
            throw new Error('IDPRODUTO é obrigatório.');
        }

        return this.client.atualizarProdutoAvulso(
            IDPRODUTO, DSNOME, IDGRUPOEMPRESARIAL, NUNCM, IDUND, UND,
            PRECOCUSTO, PRECOVENDA, IDSUBGRUPO, IDFABRICANTE, IDFORNECEDOR,
            NUREFERENCIA, IDCOR, IDTAMANHO, IDCATEGORIAPEDIDO, IDTIPOTECIDO,
            IDESTILO, IDLOCALEXPOSICAO, IDCATEGORIAS, IDTIPOPRODUTOFISCAL,
            IDFONTEPRODUTOFISCAL, STECOMMERCE, STREDESOCIAL
        );
    }

    async createProdutoAvulso({
        DSNOME, IDGRUPOEMPRESARIAL, NUNCM, IDUND, UND, PRECOCUSTO,
        PRECOVENDA, IDSUBGRUPO, IDFABRICANTE, IDFORNECEDOR, NUREFERENCIA,
        IDCOR, IDTAMANHO, IDCATEGORIAPEDIDO, IDTIPOTECIDO, IDESTILO,
        IDLOCALEXPOSICAO, IDCATEGORIAS, IDTIPOPRODUTOFISCAL,
        IDFONTEPRODUTOFISCAL, STECOMMERCE, STREDESOCIAL
    }) {
        return this.client.criarProdutoAvulso(
            DSNOME, IDGRUPOEMPRESARIAL, NUNCM, IDUND, UND, PRECOCUSTO,
            PRECOVENDA, IDSUBGRUPO, IDFABRICANTE, IDFORNECEDOR, NUREFERENCIA,
            IDCOR, IDTAMANHO, IDCATEGORIAPEDIDO, IDTIPOTECIDO, IDESTILO,
            IDLOCALEXPOSICAO, IDCATEGORIAS, IDTIPOPRODUTOFISCAL,
            IDFONTEPRODUTOFISCAL, STECOMMERCE, STREDESOCIAL
        );
    }

    async updateAlteracoesPrecoProduto({
        IDRESUMOALTERACAOPRECO,
        STAGENDAMENTOIMEDIATO,
        STAGENDAMENTOPERSONALIZADO,
        DTAGENDAMENTOPERSONALIZADO,
        STATIVO
    }) {
        if (!IDRESUMOALTERACAOPRECO) {
            throw new Error('IDRESUMOALTERACAOPRECO é obrigatório.');
        }

        return this.client.atualizarAlteracoesPrecoProduto(
            IDRESUMOALTERACAOPRECO,
            STAGENDAMENTOIMEDIATO,
            STAGENDAMENTOPERSONALIZADO,
            DTAGENDAMENTOPERSONALIZADO,
            STATIVO
        );
    }

    async createAlteracoesPrecoProduto({
        IDPRODUTO, IDEMPRESA, IDLISTAPRECO, PRECOVENDAANTIGO,
        PRECOVENDANOVO, IDUSER, STAGENDAMENTOPADRAO,
        STAGENDAMENTOIMEDIATO, STAGENDAMENTOPERSONALIZADO,
        DTAGENDAMENTOPERSONALIZADO
    }) {
        if (!IDPRODUTO) {
            throw new Error('IDPRODUTO é obrigatório.');
        }

        if (!IDEMPRESA) {
            throw new Error('IDEMPRESA é obrigatório.');
        }

        return this.client.criarAlteracoesPrecoProduto(
            IDPRODUTO, IDEMPRESA, IDLISTAPRECO, PRECOVENDAANTIGO,
            PRECOVENDANOVO, IDUSER, STAGENDAMENTOPADRAO,
            STAGENDAMENTOIMEDIATO, STAGENDAMENTOPERSONALIZADO,
            DTAGENDAMENTOPERSONALIZADO
        );
    }
}
